# Generated by Django 4.0.4 on 2022-04-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('project_info', models.TextField()),
                ('project_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
    ]
