# Generated by Django 4.0.4 on 2022-04-28 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('given_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=80)),
                ('document_number', models.CharField(max_length=30)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
    ]
